# WebTransport Router Configuration
# This file supports hot-reload - changes will be automatically detected

global:
  default_timeout: 30
  connect_timeout: 5
  log_level: INFO

services:
  # Existing services
  video:
    name: video
    host: localhost
    port: 4434
    endpoint: /process_video
    content_type: application/octet-stream
    timeout: 10
    retries: 2
    data_format: binary
    enabled: true
    custom_headers:
      X-Service-Version: "1.0"
      X-Video-Quality: "hd"

  audio:
    name: audio
    host: localhost
    port: 4435
    endpoint: /process_audio
    content_type: application/octet-stream
    timeout: 5
    retries: 3
    data_format: binary
    enabled: true
    custom_headers:
      X-Service-Version: "1.0"
      X-Audio-Codec: "opus"

  chat:
    name: chat
    host: localhost
    port: 4436
    endpoint: /process_chat
    content_type: application/json
    timeout: 3
    retries: 1
    data_format: json
    enabled: true
    custom_headers:
      X-Service-Version: "1.0"
      X-Chat-Mode: "realtime"

  # NEW SERVICES - Just add them here and they work automatically!
  
  screen:
    name: screen
    host: localhost
    port: 4437
    endpoint: /process_screen
    content_type: application/octet-stream
    timeout: 8
    retries: 2
    data_format: binary
    enabled: true  # Set to true to enable  
    custom_headers:
      X-Service-Version: "1.0"
      X-Screen-Mode: "shared"
